# Generated by Django 4.0.4 on 2022-05-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_coderegistro_user_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
